# Generated by Django 3.2.8 on 2022-02-23 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20190329_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='chef_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepies', to='recipes.category'),
        ),
    ]
